### ISSUE TITLE
CI tests are failing or not running at all

### ISSUE THREAD

**Issue by cclauss** [nodejs/node-v8#146]
Is it a problem that our CI tests are either failing or not running at all?
https://github.com/nodejs/node-v8/actions

Related to #144 ?

* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by gengjiawen** [comment]
Looks like github action problem. Happens before. It seems run now.

**Comment by cclauss** [comment]
The JS tests seem the most error prone so should we delay them so we can see if we have lint or C++ issues?  Perhaps we should change the execution order from:
Compile Node.js --> Test JS Suites --> Test C++ Suites --> Make lint  # to:
Compile Node.js --> Make lint --> Test C++ Suites --> Test JS Suites  # or:
Make lint --> Compile Node.js --> Test C++ Suites --> Test JS Suites

Lint can be a useful fast-fail and it would be good to ensure that we have no C++ problems even if JS tests fail.

**Comment by gengjiawen** [comment]
I am inclined to `Make lint --> Compile Node.js --> Test C++ Suites --> Test JS Suites`.

But there is one thing. @richardlau put some lint task in `.github/workflows/CI.yml`, should we make lint a standalone task ?

**Comment by mmarchini** [comment]
CI will eventually and periodically fail here, because the repository is automatically synced with nodejs/node and then upgraded with the latest version of V8.

If there is a specific issue when building in one platform, or a specific test failing, please open individual issues for it.

As for any changes on the Build/Test/Linter order, this should be handled on nodejs/node.

I'll close this as it doesn't seem there's anything actionable, and the Actions are green right now.
