### ISSUE TITLE
compilation error on SmartOS

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#194]
The latest canary fails to build on SmartOS.

Error:

```
10:57:12 dtrace: failed to compile script src/v8ustack.d: line 264: failed to resolve V8DBG_FRAMETYPE_ARGUMENTSADAPTORFRAME: Unknown variable name
```

@nodejs/platform-smartos could you please look into upstreaming a fix?

**Comment by cjihrig** [comment]
@targos can you cherry-pick https://github.com/cjihrig/node-v8/commit/98c618064cde164513616787b7a0e140576d6920. Since V8 has removed argument adapters, I don't think there is anything to upstream.

Here is a CI run: https://ci.nodejs.org/job/node-test-commit/44687/. At the time of writing, the CI hasn't finished yet, but the SmartOS run is green, and I don't think any other platforms depend on this code.

**Comment by targos** [comment]
Thanks @cjihrig! Cherry-picked to `canary-base`
